# Generated by Django 4.1.7 on 2023-05-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('dis', models.CharField(max_length=50)),
                ('workhour_b', models.CharField(max_length=10)),
                ('workhour_a', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('slot', models.TimeField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clinic')),
            ],
        ),
    ]
