# Generated by Django 4.1.7 on 2023-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookings_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='workhour_a',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='workhour_b',
            field=models.CharField(max_length=50),
        ),
    ]
